/*
 * RingCentral Glip REST API
 * API Explorer for RingCentral Glip Messaging API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * Group
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T22:29:16.640Z")
public class Group {
  @SerializedName("id")
  private String id = null;

  /**
   * Type of group. Must be set to 'Group'
   */
  public enum TypeEnum {
    @SerializedName("Group")
    GROUP("Group");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("type")
  private TypeEnum type = null;

  @SerializedName("members")
  private List<String> members = new ArrayList<String>();

  @SerializedName("isPublic")
  private Boolean isPublic = null;

  @SerializedName("creationTime")
  private String creationTime = null;

  @SerializedName("lastModifiedTime")
  private String lastModifiedTime = null;

  public Group id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Id of group
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "Id of group")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Group type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Type of group. Must be set to 'Group'
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "Type of group. Must be set to 'Group'")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public Group members(List<String> members) {
    this.members = members;
    return this;
  }

  public Group addMembersItem(String membersItem) {
    this.members.add(membersItem);
    return this;
  }

   /**
   * Array of group participants
   * @return members
  **/
  @ApiModelProperty(example = "null", value = "Array of group participants")
  public List<String> getMembers() {
    return members;
  }

  public void setMembers(List<String> members) {
    this.members = members;
  }

  public Group isPublic(Boolean isPublic) {
    this.isPublic = isPublic;
    return this;
  }

   /**
   * Group couldn't be public
   * @return isPublic
  **/
  @ApiModelProperty(example = "null", value = "Group couldn't be public")
  public Boolean getIsPublic() {
    return isPublic;
  }

  public void setIsPublic(Boolean isPublic) {
    this.isPublic = isPublic;
  }

  public Group creationTime(String creationTime) {
    this.creationTime = creationTime;
    return this;
  }

   /**
   * Time of creation (ISO format)
   * @return creationTime
  **/
  @ApiModelProperty(example = "null", value = "Time of creation (ISO format)")
  public String getCreationTime() {
    return creationTime;
  }

  public void setCreationTime(String creationTime) {
    this.creationTime = creationTime;
  }

  public Group lastModifiedTime(String lastModifiedTime) {
    this.lastModifiedTime = lastModifiedTime;
    return this;
  }

   /**
   * Time of last modification (ISO format)
   * @return lastModifiedTime
  **/
  @ApiModelProperty(example = "null", value = "Time of last modification (ISO format)")
  public String getLastModifiedTime() {
    return lastModifiedTime;
  }

  public void setLastModifiedTime(String lastModifiedTime) {
    this.lastModifiedTime = lastModifiedTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Group group = (Group) o;
    return Objects.equals(this.id, group.id) &&
        Objects.equals(this.type, group.type) &&
        Objects.equals(this.members, group.members) &&
        Objects.equals(this.isPublic, group.isPublic) &&
        Objects.equals(this.creationTime, group.creationTime) &&
        Objects.equals(this.lastModifiedTime, group.lastModifiedTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, members, isPublic, creationTime, lastModifiedTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Group {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    members: ").append(toIndentedString(members)).append("\n");
    sb.append("    isPublic: ").append(toIndentedString(isPublic)).append("\n");
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("    lastModifiedTime: ").append(toIndentedString(lastModifiedTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

