/*
 * RingCentral Glip REST API
 * API Explorer for RingCentral Glip Messaging API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * InlineResponse2003Records
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T22:29:16.640Z")
public class InlineResponse2003Records {
  @SerializedName("id")
  private String id = null;

  @SerializedName("creatorId")
  private String creatorId = null;

  @SerializedName("groupId")
  private String groupId = null;

  @SerializedName("text")
  private Boolean text = null;

  @SerializedName("creationTime")
  private String creationTime = null;

  @SerializedName("lastModifiedTime")
  private String lastModifiedTime = null;

  public InlineResponse2003Records id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Id of post
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "Id of post")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public InlineResponse2003Records creatorId(String creatorId) {
    this.creatorId = creatorId;
    return this;
  }

   /**
   * Id of person created post
   * @return creatorId
  **/
  @ApiModelProperty(example = "null", value = "Id of person created post")
  public String getCreatorId() {
    return creatorId;
  }

  public void setCreatorId(String creatorId) {
    this.creatorId = creatorId;
  }

  public InlineResponse2003Records groupId(String groupId) {
    this.groupId = groupId;
    return this;
  }

   /**
   * Id of group oist belongs to
   * @return groupId
  **/
  @ApiModelProperty(example = "null", value = "Id of group oist belongs to")
  public String getGroupId() {
    return groupId;
  }

  public void setGroupId(String groupId) {
    this.groupId = groupId;
  }

  public InlineResponse2003Records text(Boolean text) {
    this.text = text;
    return this;
  }

   /**
   * Text of message
   * @return text
  **/
  @ApiModelProperty(example = "null", value = "Text of message")
  public Boolean getText() {
    return text;
  }

  public void setText(Boolean text) {
    this.text = text;
  }

  public InlineResponse2003Records creationTime(String creationTime) {
    this.creationTime = creationTime;
    return this;
  }

   /**
   * Time of creation (ISO format)
   * @return creationTime
  **/
  @ApiModelProperty(example = "null", value = "Time of creation (ISO format)")
  public String getCreationTime() {
    return creationTime;
  }

  public void setCreationTime(String creationTime) {
    this.creationTime = creationTime;
  }

  public InlineResponse2003Records lastModifiedTime(String lastModifiedTime) {
    this.lastModifiedTime = lastModifiedTime;
    return this;
  }

   /**
   * Time of last modification (ISO format)
   * @return lastModifiedTime
  **/
  @ApiModelProperty(example = "null", value = "Time of last modification (ISO format)")
  public String getLastModifiedTime() {
    return lastModifiedTime;
  }

  public void setLastModifiedTime(String lastModifiedTime) {
    this.lastModifiedTime = lastModifiedTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2003Records inlineResponse2003Records = (InlineResponse2003Records) o;
    return Objects.equals(this.id, inlineResponse2003Records.id) &&
        Objects.equals(this.creatorId, inlineResponse2003Records.creatorId) &&
        Objects.equals(this.groupId, inlineResponse2003Records.groupId) &&
        Objects.equals(this.text, inlineResponse2003Records.text) &&
        Objects.equals(this.creationTime, inlineResponse2003Records.creationTime) &&
        Objects.equals(this.lastModifiedTime, inlineResponse2003Records.lastModifiedTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, creatorId, groupId, text, creationTime, lastModifiedTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2003Records {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    creatorId: ").append(toIndentedString(creatorId)).append("\n");
    sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("    lastModifiedTime: ").append(toIndentedString(lastModifiedTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

