/*
 * RingCentral Glip REST API
 * API Explorer for RingCentral Glip Messaging API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.InlineResponse2002Navigation;
import io.swagger.client.model.InlineResponse2003Records;
import java.util.ArrayList;
import java.util.List;

/**
 * ReadPostsResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-14T22:29:16.640Z")
public class ReadPostsResponse {
  @SerializedName("records")
  private List<InlineResponse2003Records> records = new ArrayList<InlineResponse2003Records>();

  @SerializedName("navigation")
  private InlineResponse2002Navigation navigation = null;

  public ReadPostsResponse records(List<InlineResponse2003Records> records) {
    this.records = records;
    return this;
  }

  public ReadPostsResponse addRecordsItem(InlineResponse2003Records recordsItem) {
    this.records.add(recordsItem);
    return this;
  }

   /**
   * a list of post objects within a response envelope
   * @return records
  **/
  @ApiModelProperty(example = "null", value = "a list of post objects within a response envelope")
  public List<InlineResponse2003Records> getRecords() {
    return records;
  }

  public void setRecords(List<InlineResponse2003Records> records) {
    this.records = records;
  }

  public ReadPostsResponse navigation(InlineResponse2002Navigation navigation) {
    this.navigation = navigation;
    return this;
  }

   /**
   * Get navigation
   * @return navigation
  **/
  @ApiModelProperty(example = "null", value = "")
  public InlineResponse2002Navigation getNavigation() {
    return navigation;
  }

  public void setNavigation(InlineResponse2002Navigation navigation) {
    this.navigation = navigation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReadPostsResponse readPostsResponse = (ReadPostsResponse) o;
    return Objects.equals(this.records, readPostsResponse.records) &&
        Objects.equals(this.navigation, readPostsResponse.navigation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(records, navigation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReadPostsResponse {\n");
    
    sb.append("    records: ").append(toIndentedString(records)).append("\n");
    sb.append("    navigation: ").append(toIndentedString(navigation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

