/*
 * RingCentral Glip REST API
 * API Explorer for RingCentral Glip Messaging API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.InlineResponse2001;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CompanyApi
 */
@Ignore
public class CompanyApiTest {

    private final CompanyApi api = new CompanyApi();

    
    /**
     * Get Company Info
     *
     * Returns a company by id
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void companiesCompanyIdGetTest() throws ApiException {
        String companyId = null;
        InlineResponse2001 response = api.companiesCompanyIdGet(companyId);

        // TODO: test validations
    }
    
}
