/*
 * RingCentral Glip REST API
 * API Explorer for RingCentral Glip Messaging API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.InlineResponse2002;
import io.swagger.client.model.InlineResponse2002Records;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GroupApi
 */
@Ignore
public class GroupApiTest {

    private final GroupApi api = new GroupApi();

    
    /**
     * Return groups associated with current user
     *
     * Return groups associated with current user
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void groupsGetTest() throws ApiException {
        String type = null;
        String pageToken = null;
        Integer recordCount = null;
        InlineResponse2002 response = api.groupsGet(type, pageToken, recordCount);

        // TODO: test validations
    }
    
    /**
     * Returns a group by id
     *
     * Returns a group by id
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void groupsGroupIdGetTest() throws ApiException {
        String groupId = null;
        InlineResponse2002Records response = api.groupsGroupIdGet(groupId);

        // TODO: test validations
    }
    
}
