/*
 * RingCentral Glip REST API
 * API Explorer for RingCentral Glip Messaging API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.InlineResponse200;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PersonApi
 */
@Ignore
public class PersonApiTest {

    private final PersonApi api = new PersonApi();

    
    /**
     * Get Person by ID
     *
     * Returns a person by id. If the person cannot be accessed by current user, API must return HTTP 404.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void personsPersonIdGetTest() throws ApiException {
        String personId = null;
        InlineResponse200 response = api.personsPersonIdGet(personId);

        // TODO: test validations
    }
    
}
