/*
 * RingCentral Glip REST API
 * API Explorer for RingCentral Glip Messaging API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Body;
import io.swagger.client.model.InlineResponse2003;
import io.swagger.client.model.InlineResponse2003Records;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PostApi
 */
@Ignore
public class PostApiTest {

    private final PostApi api = new PostApi();

    
    /**
     * Get User Posts
     *
     * Return posts which are available for current user. Not more than 250 records to be returned in one request. If posts cannot be viewed by current user (fro example, user is not member of group), API must return HTTP 404.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postsGetTest() throws ApiException {
        String groupId = null;
        String pageToken = null;
        String recordCount = null;
        InlineResponse2003 response = api.postsGet(groupId, pageToken, recordCount);

        // TODO: test validations
    }
    
    /**
     * Send New Message
     *
     * Creates post and send it to specified Group and returns it.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postsPostTest() throws ApiException {
        Body body = null;
        InlineResponse2003Records response = api.postsPost(body);

        // TODO: test validations
    }
    
    /**
     * Get Post By Id
     *
     * Returns post with given id. If a post cannot be viewed by current user, API must return HTTP 404.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postsPostIdGetTest() throws ApiException {
        String postId = null;
        InlineResponse2003Records response = api.postsPostIdGet(postId);

        // TODO: test validations
    }
    
}
